#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 22 15:13:35 VET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.4.zip
